export const FETCH_ORDERDETAILS_REQUEST = "FETCH_ORDERDETAILS_REQUEST";
export const FETCH_ORDERDETAILS_SUCCESS = "FETCH_ORDERDETAILS_SUCCESS";
export const FETCH_ORDERDETAILS_FAILURE = "FETCH_ORDERDETAILS_FAILURE";
