export const FETCH_MAIN_CATEGORY_REQUEST =  'FETCH_MAIN_CATEGORY_REQUEST'
export const FETCH_MAIN_CATEGORY_SUCCESS =  'FETCH_MAIN_CATEGORY_SUCCESS'
export const FETCH_MAIN_CATEGORY_FAILURE =  'FETCH_MAIN_CATEGORY_FAILURE'