export const  ADD_CART_DATA=  ' ADD_CART_DATA',
REMOVE_PRODUCT = 'REMOVE_PRODUCT',
INCREASE_QUANTITY = 'INCREASE_QUANTITY',
DECREASE_QUANTITY = 'DECREASE_QUANTITY',
EMPTY_CART_CONTENT = 'EMPTY_CART_CONTENT';
