export const FETCH_SUBCATEGORY_REQUEST =  'FETCH_SUBCATEGORY_REQUEST'
export const FETCH_SUBCATEGORY_SUCCESS =  'FETCH_SUBCATEGORY_SUCCESS'
export const FETCH_SUBCATEGORY_FAILURE =  'FETCH_SUBCATEGORY_FAILURE'